---

#### Network Setting ####

# OVS type setting,
# Supported: ovs, dpdk. ("ovs" is for pure ovs, "dpdk" is for dpdk + ovs)
ovs_type: dpdk

# DPDK version
dpdk_version: 17.11.2

# Hugepages size
nr_hugepages: 1024


### Open vSwitch install ###
# ovs_access_mode: Is ovs tar file can be access? (public or private)
ovs_access_mode: private

# Open vSwitch version, If ovs_access_mode is public, please set ovs_version.
ovs_version: 2.9.2

# ovs_tar_path: If ovs_access_mode is private, you need to setting ovs_tar_path which is in ansible host. (No '/' in the end line.)
ovs_tar_path: /tmp/openvswitch-2.9.2.tar.gz
ovs_folder_name: openvswitch-2.9.2

### Kernel module ###
kernel_module: uio
